type: 'kitti'
root_dir: '/mnt/disk1/tjc/code/LPCG'

data_dir: '/mnt/disk1/tjc/code/LPCG/data/kitti'
raw_data_dir: '/mnt/disk1/tjc/code/LPCG/data/kitti/raw_data'
KITTI3D_data_dir: '/mnt/disk1/tjc/code/LPCG/data/kitti/KITTI3D/training'
KITTI_merge_data_dir: '/mnt/disk1/tjc/code/LPCG/data/kitti/kitti_merge/training'

# writelist: ['Car']
writelist: ['Car', 'Pedestrian', 'Cyclist'] # 需要保留的目标类别
label_mode: ['low_cost']
#optional: label_mode: ['low_cost'] or label_mode: ['high_acc', 'low_cost']

