import config_mots.car_test_se_to_save
import config_mots.car_test_tracking_val
import config_mots.car_finetune_tracking
import config_mots.car_finetune_SE_crop
import config_mots.car_finetune_SE_mots
import config_mots.car_test_KITTI_raw_data_SpatialEmbedding_to_save
import config_mots.car_test_KITTI_raw_data_PointTrack_to_save